name: Alerta Discord

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta ao Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Novo commit no repositório!"
          description: |
            Repositório: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            Autor: ${{ github.actor }}
          color: 0x00ff00